version: "3.5"

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    command: yarn start
    depends_on:
      - api
    volumes:
      - './web/yarn.lock:/home/node/app/yarn.lock'
      - './web/node_modules:/home/node/app/node_modules'
      - './web:/home/node/app/'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - REACT_API_HOST=api
      - REACT_API_PORT=6000

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    command: rails s -b 0.0.0.0 -p 6000
    depends_on:
      - postgres
    environment:
      - DB_USERNAME=atm
      - DB_PASSWORD=atm
      - DB_HOST=postgres
    volumes:
      - "./api:/home/backend/app"
      - "./api/.docker/bundle:/usr/local/bundle"
      - "./api/./config/entrypoint.sh:/usr/bin/entrypoint.sh"

  postgres:
    image: postgres:13-alpine
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - ./api/.docker/init/create_user.sql:/docker-entrypoint-initdb.d/000-data.sql
      - ./api/.docker/db/.postgres/12/data:/var/lib/postgresql/data
