default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') { 'atm_development' } %>

test:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') { 'atm_test' } %>

production:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') { 'atm_production' } %>
