version: '3.5'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn start
    volumes:
      - './yarn.lock:/home/node/app/yarn.lock'
      - './node_modules:/home/node/app/node_modules'
      - '.:/home/node/app/'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - REACT_APP_API_HOST=http://localhost
      - REACT_APP_API_PORT=3003
